# Generated by Django 4.2.4 on 2023-09-11 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('host_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersAndUptime.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='Uptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.DateTimeField(unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersAndUptime.hostname')),
            ],
        ),
    ]
