# Generated by Django 4.2.4 on 2023-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAndUptime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
