# Generated by Django 4.2.4 on 2023-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAndUptime', '0002_alter_users_group_name_alter_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
