# Generated by Django 4.2.4 on 2023-09-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAndUptime', '0003_alter_users_group_name_alter_users_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uptime',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='host_name',
        ),
        migrations.DeleteModel(
            name='HostName',
        ),
        migrations.DeleteModel(
            name='Uptime',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
