# Generated by Django 4.2.4 on 2023-08-31 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windowsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osname',
            name='os_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='OSVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_version', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
    ]
