# Generated by Django 4.2.4 on 2023-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windowsAPI', '0002_alter_osname_os_name_osversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osversion',
            name='os_version',
            field=models.CharField(max_length=255),
        ),
    ]
