# Generated by Django 4.2.4 on 2023-09-01 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windowsAPI', '0003_alter_osversion_os_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osversion',
            name='os_version',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='WindowsDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_dir', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_model', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='SystemBootTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_boot_time', models.DateTimeField()),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='RegOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_owner', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='OSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_config', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='OSBuildType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_build_type', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='LogonServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logon_server', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='BootDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot_device', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
        migrations.CreateModel(
            name='BIOSVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bios_version', models.CharField(max_length=255, unique=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windowsAPI.hostname')),
            ],
        ),
    ]
