# Generated by Django 4.2.4 on 2023-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windowsAPI', '0004_alter_osversion_os_version_windowsdir_systemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemboottime',
            name='system_boot_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
